import { HttpStatus } from '@nestjs/common';

export const PG_ERROR_CODES = {
  UNIQUE_VIOLATION: '23505',
  FOREIGN_KEY_VIOLATION: '23503',
  NOT_NULL_VIOLATION: '23502',
  CHECK_VIOLATION: '23514',
  STRING_DATA_RIGHT_TRUNCATION: '22001',
  UNDEFINED_COLUMN: '42703',
  UNDEFINED_TABLE: '42P01',
  SYNTAX_ERROR: '42601',
  SERIALIZATION_FAILURE: '40001',
} as const;

export const PG_ERROR_MAP: Record<string, HttpStatus> = {
  [PG_ERROR_CODES.UNIQUE_VIOLATION]: HttpStatus.CONFLICT,
  [PG_ERROR_CODES.FOREIGN_KEY_VIOLATION]: HttpStatus.BAD_REQUEST,
  [PG_ERROR_CODES.NOT_NULL_VIOLATION]: HttpStatus.BAD_REQUEST,
  [PG_ERROR_CODES.CHECK_VIOLATION]: HttpStatus.BAD_REQUEST,
  [PG_ERROR_CODES.STRING_DATA_RIGHT_TRUNCATION]: HttpStatus.BAD_REQUEST,
  [PG_ERROR_CODES.UNDEFINED_COLUMN]: HttpStatus.BAD_REQUEST,
  [PG_ERROR_CODES.UNDEFINED_TABLE]: HttpStatus.BAD_REQUEST,
  [PG_ERROR_CODES.SYNTAX_ERROR]: HttpStatus.BAD_REQUEST,
  [PG_ERROR_CODES.SERIALIZATION_FAILURE]: HttpStatus.SERVICE_UNAVAILABLE,
};
